import 'package:flutter/material.dart';

// ─────────────────────────────────────────────
// DATA — Sri Lanka destinations (real coordinates and Unsplash photos)
// ─────────────────────────────────────────────
final List<Map<String, dynamic>> kDestinations = [
  {
    'name': 'Sigiriya',
    'country': 'Sri Lanka',
    'tag': 'Ancient Wonder',
    'category': 'Mountain',
    'tagColor': Colors.orange,
    'img': 'https://images.pexels.com/photos/13391116/pexels-photo-13391116.jpeg?auto=compress&cs=tinysrgb&w=800',
    'description':
        'Sigiriya is an ancient rock fortress in the Matale District of Sri Lanka. Rising nearly 200 metres above the surrounding plains, this UNESCO World Heritage Site features the remains of a 5th-century royal palace, stunning frescoes, mirror walls, and beautifully landscaped water gardens.',
    'highlights': ['Lion Rock Summit', 'Ancient Frescoes', 'Water Gardens', 'Mirror Wall'],
    'bestTime': 'Jan – Apr',
    'rating': 4.9,
    'cost': '\$25 entry',
    'duration': '1 day',
    'lat': 7.9570,
    'lng': 80.7603,
    'subLocations': [
      {
        'name': 'Pidurangala Rock',
        'category': 'Sight',
        'description': 'A massive rock formation adjacent to Sigiriya, offering a moderately challenging climb and spectacular panoramic views of Sigiriya Lion Rock.',
        'rating': 4.8,
        'price': 3.0,
        'img': 'https://images.unsplash.com/photo-1598971861713-54ad16a7e72e?w=800&q=80',
        'lat': 7.9620,
        'lng': 80.7650,
        'highlights': ['360 Panorama', 'Sigiriya Rock Views', 'Buddhist Cave Temple'],
      },
      {
        'name': 'Sigiriya Archaeological Museum',
        'category': 'Sight',
        'description': 'A modern archaeological museum showcasing artifacts, models, and history of the Sigiriya complex and 5th-century gardens.',
        'rating': 4.5,
        'price': 5.0,
        'img': 'https://images.unsplash.com/photo-1590073844006-33379778ae09?w=800&q=80',
        'lat': 7.9535,
        'lng': 80.7580,
        'highlights': ['5th Century Relics', 'Interactive Scale Models', 'Historic Documentaries'],
      },
      {
        'name': 'Hotel Sigiriya',
        'category': 'Stay',
        'description': 'An iconic resort located right in front of the Sigiriya rock, featuring a stunning pool view and eco-friendly hospitality.',
        'rating': 4.7,
        'price': 110.0,
        'img': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
        'lat': 7.9592,
        'lng': 80.7548,
        'amenities': ['Swimming Pool', 'Rock View Deck', 'Ayurweda Spa', 'Free Wi-Fi'],
        'highlights': ['Unmatched Rock Views', 'Eco-friendly Design', 'Traditional Buffet'],
      },
      {
        'name': 'Aliya Resort & Spa',
        'category': 'Stay',
        'description': 'A themed luxury resort celebrating the elephant, offering chalets and tents with spectacular views of the central plains.',
        'rating': 4.6,
        'price': 135.0,
        'img': 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
        'lat': 7.9355,
        'lng': 80.7188,
        'amenities': ['Infinity Pool', 'Ayurveda Spa', 'Gym', 'Multiple Restaurants'],
        'highlights': ['Elephant Themes', 'Luxury Chalets', 'Quiet Location'],
      },
      {
        'name': 'Kenoli Restaurant',
        'category': 'Eat',
        'description': 'A top local dining spot famous for serving authentic, spicy Sri Lankan rice and curry buffet in a traditional clay-pot setting.',
        'rating': 4.6,
        'price': 8.0,
        'img': 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
        'lat': 7.9540,
        'lng': 80.7520,
        'highlights': ['Spicy Rice & Curry Buffet', 'Claypot Traditional Cooking', 'Fresh Mango Chutney'],
      },
      {
        'name': 'Pradeep Restaurant',
        'category': 'Eat',
        'description': 'A friendly family-run restaurant serving great local and western bites with cold beverages near the Sigiriya entrance.',
        'rating': 4.5,
        'price': 10.0,
        'img': 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800&q=80',
        'lat': 7.9548,
        'lng': 80.7540,
        'highlights': ['Devilled Chicken', 'Fresh Coconut Hoppers', 'Western Breakfasts'],
      },
      {
        'name': 'Sigiriya Backpackers Hostel',
        'category': 'Budget',
        'description': 'A highly rated hostel with bunk beds, shared lounge, and rental bicycles, popular with budget backpackers.',
        'rating': 4.4,
        'price': 10.0,
        'img': 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80',
        'lat': 7.9480,
        'lng': 80.7510,
        'amenities': ['Bunk Beds', 'Free Wi-Fi', 'Bicycle Rental', 'Shared Kitchen'],
        'highlights': ['Social Lounge', 'Cheapest Beds', 'Bicycle Tours'],
      },
      {
        'name': 'Pidurangala Homestay',
        'category': 'Budget',
        'description': 'A simple, cozy homestay hosted by a local family, located just minutes from the Pidurangala climbing start point.',
        'rating': 4.5,
        'price': 15.0,
        'img': 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80',
        'lat': 7.9640,
        'lng': 80.7670,
        'highlights': ['Traditional Family Cooking', 'Minutes to Hiking Path', 'Quiet Jungle Retreat'],
      }
    ],
  },
  {
    'name': 'Galle Fort',
    'country': 'Sri Lanka',
    'tag': 'Colonial Heritage',
    'category': 'Temple',
    'tagColor': Colors.blue,
    'img': 'https://images.unsplash.com/photo-1765833437191-9dc9992db439?w=800&q=80',
    'description':
        'Galle Fort is a historic fortified city on the southwestern tip of Sri Lanka, built by the Portuguese and later fortified by the Dutch. This UNESCO site blends European architecture with South Asian traditions.',
    'highlights': ['Dutch Reformed Church', 'Lighthouse', 'Ocean Ramparts', 'Old Bazaar'],
    'bestTime': 'Nov – Apr',
    'rating': 4.7,
    'cost': 'Free entry',
    'duration': '1-2 days',
    'lat': 6.0286,
    'lng': 80.2168,
    'subLocations': [
      {
        'name': 'Galle Lighthouse',
        'category': 'Sight',
        'description': "Sri Lanka's oldest light station, a picturesque white lighthouse standing on the ramparts of Galle Fort, surrounded by palm trees.",
        'rating': 4.8,
        'price': 0.0,
        'img': 'https://images.unsplash.com/photo-1765833437191-9dc9992db439?w=800&q=80',
        'lat': 6.0261,
        'lng': 80.2185,
        'highlights': ['Iconic Photo Spot', 'Rampart Coast View', 'Historic Landmark'],
      },
      {
        'name': 'Dutch Reformed Church',
        'category': 'Sight',
        'description': 'Built in 1755, this belfry and church contain stone gravestones and historic colonial relics from the Dutch era.',
        'rating': 4.6,
        'price': 0.0,
        'img': 'https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?w=800&q=80',
        'lat': 6.0278,
        'lng': 80.2172,
        'highlights': ['Dutch Belfry', 'Historic Tombstones', 'Unique Architecture'],
      },
      {
        'name': 'Fort Bazaar Hotel',
        'category': 'Stay',
        'description': 'A premium boutique hotel set in a restored 17th-century merchant house, featuring a chic courtyard and middle-eastern dining.',
        'rating': 4.8,
        'price': 160.0,
        'img': 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80',
        'lat': 6.0280,
        'lng': 80.2170,
        'amenities': ['Boutique Spa', 'Fine Dining Court', 'Free Wi-Fi', 'Library Bar'],
        'highlights': ['17th Century House', 'Chic Courtyard', 'Luxury Linens'],
      },
      {
        'name': 'Galle Fort Hotel',
        'category': 'Stay',
        'description': 'A heritage luxury hotel blending grand colonial style and architecture in the center of Galle Fort.',
        'rating': 4.7,
        'price': 180.0,
        'img': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
        'lat': 6.0292,
        'lng': 80.2162,
        'amenities': ['Swimming Pool', 'Heritage Bar', 'Free Wi-Fi', 'Airport Shuttles'],
        'highlights': ['Geoffrey Bawa Elements', 'Antique Furniture', 'Gourmet Crab Curry'],
      },
      {
        'name': "Pedlar's Inn Cafe",
        'category': 'Eat',
        'description': 'A cozy and historical cafe inside the fort serving excellent Italian coffees, fresh salads, local crab, and wood-fired pizzas.',
        'rating': 4.6,
        'price': 12.0,
        'img': 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80',
        'lat': 6.0275,
        'lng': 80.2178,
        'highlights': ['Handmade Pasta', 'Chilled Fresh Fruit Juices', 'Charming Historical Interiors'],
      },
      {
        'name': 'Poonas Restaurant',
        'category': 'Eat',
        'description': 'Trendy local fusion diner known for creative seafood bowls, traditional hopper platters, and organic juices.',
        'rating': 4.5,
        'price': 15.0,
        'img': 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
        'lat': 6.0284,
        'lng': 80.2165,
        'highlights': ['Seafood Hopper Platters', 'Organic Smoothie Bowls', 'Central Fort Location'],
      },
      {
        'name': 'Galle Fort Hostel',
        'category': 'Budget',
        'description': 'A charming colonial budget house inside the fort walls offering clean bunk beds, local breakfasts, and travel tips.',
        'rating': 4.4,
        'price': 12.0,
        'img': 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80',
        'lat': 6.0290,
        'lng': 80.2160,
        'amenities': ['Bunk Beds', 'Free Breakfast', 'Free Wi-Fi', 'Locker Room'],
        'highlights': ['Colonial Charm', 'Friendly Backpacker Vibe', 'Rooftop Terrace'],
      },
      {
        'name': "Pilgrim's Resthouse",
        'category': 'Budget',
        'description': 'A popular backpacker resthouse offering twin beds, roof terrace views, and surf gear hire.',
        'rating': 4.3,
        'price': 14.0,
        'img': 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80',
        'lat': 6.0270,
        'lng': 80.2180,
        'highlights': ['Cheapest Twin Rooms', 'Surfboards for Rent', 'Overlooking Ramparts'],
      }
    ],
  },
  {
    'name': 'Mirissa Beach',
    'country': 'Sri Lanka',
    'tag': 'Coastal Paradise',
    'category': 'Beach',
    'tagColor': Colors.cyan,
    'img': 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?w=800&q=80',
    'description':
        'Mirissa is a coastal town on the southern tip of Sri Lanka, renowned for its crescent-shaped beach, vibrant nightlife, and world-class whale watching between November and April.',
    'highlights': ['Whale Watching', 'Coconut Tree Hill', 'Surfing', 'Secret Beach'],
    'bestTime': 'Nov – Apr',
    'rating': 4.6,
    'cost': '\$30 whale tour',
    'duration': '2-3 days',
    'lat': 5.9483,
    'lng': 80.4536,
    'subLocations': [
      {
        'name': 'Coconut Tree Hill',
        'category': 'Sight',
        'description': 'A unique, dome-like headland covered with tall coconut palms, offering a picturesque view of the red cliff cliffs and blue bay.',
        'rating': 4.8,
        'price': 0.0,
        'img': 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?w=800&q=80',
        'lat': 5.9427,
        'lng': 80.4632,
        'highlights': ['Tall Palms Dome', 'Sunset View Point', 'Instagram Landscape'],
      },
      {
        'name': 'Parrot Rock Bridge',
        'category': 'Sight',
        'description': 'A tiny rocky island situated right on the shore of Mirissa, climbable via a simple bamboo bridge for panoramic coastal views.',
        'rating': 4.5,
        'price': 0.0,
        'img': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
        'lat': 5.9465,
        'lng': 80.4580,
        'highlights': ['Bamboo Crossing', 'High Tide Adventure', 'Panoramic Bay View'],
      },
      {
        'name': 'Mandara Resort',
        'category': 'Stay',
        'description': 'A premium beachfront resort located in a quiet enclave, offering private pools, ocean view dining, and boat hires.',
        'rating': 4.7,
        'price': 130.0,
        'img': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
        'lat': 5.9490,
        'lng': 80.4480,
        'amenities': ['Private Pool', 'Beachfront Restaurant', 'Free Wi-Fi', 'Whale Tours'],
        'highlights': ['Quiet Bay Location', 'Luxury Private Pools', 'Seafood Grill'],
      },
      {
        'name': 'Paradise Beach Club',
        'category': 'Stay',
        'description': 'Directly located on Mirissa beach, featuring comfortable rooms, surf access, and beachside barbecue nights under the stars.',
        'rating': 4.6,
        'price': 115.0,
        'img': 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
        'lat': 5.9482,
        'lng': 80.4550,
        'amenities': ['Outdoor Pool', 'Beach Bar', 'Surf Lessons', 'Free Wi-Fi'],
        'highlights': ['Right on Beachfront', 'Beach Parties', 'Starry Barbecue Nights'],
      },
      {
        'name': 'Zephyr Restaurant',
        'category': 'Eat',
        'description': 'Famous beachfront restaurant serving fresh crab curry, grilled fish, and signature tropical cocktails with beach vibes.',
        'rating': 4.6,
        'price': 16.0,
        'img': 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
        'lat': 5.9468,
        'lng': 80.4572,
        'highlights': ['Signature Crab Curry', 'Fresh Sea Bass', 'Chic Beach Dining'],
      },
      {
        'name': 'Shady Lane Mirissa',
        'category': 'Eat',
        'description': 'Popular hipster spot for delicious avocado toast, colorful smoothie bowls, and fresh local fruit juices.',
        'rating': 4.5,
        'price': 10.0,
        'img': 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800&q=80',
        'lat': 5.9490,
        'lng': 80.4545,
        'highlights': ['Avocado Toast', 'Acai Smoothie Bowls', 'Organic Espresso'],
      },
      {
        'name': "JJ's Hostel Mirissa",
        'category': 'Budget',
        'description': 'High-end, highly social backpacker hostel with shared garden terrace, lockers, and daily group tours.',
        'rating': 4.8,
        'price': 15.0,
        'img': 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80',
        'lat': 5.9510,
        'lng': 80.4520,
        'amenities': ['Bunk Beds', 'Shared Terrace', 'Social Bar', 'Free Wi-Fi'],
        'highlights': ['High-End Bunks', 'Rooftop Chill Area', 'Daily Surfing Tours'],
      },
      {
        'name': 'Mirissa Surf Backpackers',
        'category': 'Budget',
        'description': 'Simple beachfront guesthouse with cheap dorms, clean showers, and hammocks under the trees.',
        'rating': 4.3,
        'price': 11.0,
        'img': 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80',
        'lat': 5.9450,
        'lng': 80.4610,
        'highlights': ['Beachfront Hammocks', 'Cheap Dorm Beds', 'Surf Rental Discounts'],
      }
    ],
  },
  {
    'name': 'Kandy',
    'country': 'Sri Lanka',
    'tag': 'Cultural Capital',
    'category': 'Temple',
    'tagColor': Colors.purple,
    'img': 'https://images.unsplash.com/photo-1665849050332-8d5d7e59afb6?w=800&q=80',
    'description':
        "Kandy is Sri Lanka's cultural capital, home to the sacred Temple of the Tooth Relic. Surrounded by a beautiful lake and lush mountains, the city hosts the spectacular Esala Perahera festival each year.",
    'highlights': ['Temple of the Tooth', 'Kandy Lake', 'Royal Botanical Gardens', 'Esala Perahera'],
    'bestTime': 'Jan – Apr',
    'rating': 4.8,
    'cost': '\$15 entry',
    'duration': '2 days',
    'lat': 7.2906,
    'lng': 80.6337,
    'subLocations': [
      {
        'name': 'Temple of the Tooth Relic',
        'category': 'Sight',
        'description': "Sri Lanka's most sacred Buddhist temple, situated in the royal palace complex, housing the tooth relic of the Buddha.",
        'rating': 4.9,
        'price': 15.0,
        'img': 'https://images.unsplash.com/photo-1665849050332-8d5d7e59afb6?w=800&q=80',
        'lat': 7.2936,
        'lng': 80.6413,
        'highlights': ['Sacred Tooth Casket', 'Royal Palace Grounds', 'Daily Puja Ceremonies'],
      },
      {
        'name': 'Royal Botanical Gardens Peradeniya',
        'category': 'Sight',
        'description': 'Renowned for its collection of orchids, giant palm avenues, medical herbs, and massive Javan fig tree spanning 2,500 square meters.',
        'rating': 4.7,
        'price': 10.0,
        'img': 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80',
        'lat': 7.2718,
        'lng': 80.5966,
        'highlights': ['Giant Orchid House', 'Palm Tree Avenue', 'Historic 2000s Fig Tree'],
      },
      {
        'name': 'The Grand Kandyan',
        'category': 'Stay',
        'description': 'A luxurious 5-star hotel perched on a hill, offering royal interiors, panoramic mountain views, and a large rooftop pool.',
        'rating': 4.8,
        'price': 140.0,
        'img': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
        'lat': 7.2995,
        'lng': 80.6440,
        'amenities': ['Rooftop Pool', 'Luxury Spa', 'Fitness Gym', 'Free Wi-Fi'],
        'highlights': ['Royal Hilltop Views', 'Grand Interiors', 'Signature Sri Lankan Buffet'],
      },
      {
        'name': "Earl's Regency",
        'category': 'Stay',
        'description': 'Nestled in the Tennekumbura hills, this luxury resort offers scenic river views and traditional Kandyan hospitality.',
        'rating': 4.7,
        'price': 120.0,
        'img': 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
        'lat': 7.2915,
        'lng': 80.6720,
        'amenities': ['Swimming Pool', 'Spa Resort', 'Mahaweli River View', 'Free Wi-Fi'],
        'highlights': ['Tranquil Forest Hills', 'Traditional Dining Halls', 'Premium Rooms'],
      },
      {
        'name': 'Slightly Chilled Lounge',
        'category': 'Eat',
        'description': 'Top-rated rooftop restaurant and bar overlooking Kandy Lake, serving great local curries, Chinese fusion, and cold beers.',
        'rating': 4.6,
        'price': 12.0,
        'img': 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
        'lat': 7.2942,
        'lng': 80.6448,
        'highlights': ['Sunset Rooftop View', 'Chilled Local Lion Beer', 'Sizzling Chinese Bowls'],
      },
      {
        'name': 'Devon Restaurant',
        'category': 'Eat',
        'description': 'A busy local bakery and diner, famous for traditional hoppers, spicy short-eats, and authentic rice and curry plates.',
        'rating': 4.4,
        'price': 8.0,
        'img': 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800&q=80',
        'lat': 7.2910,
        'lng': 80.6355,
        'highlights': ['Short-eats Pastries', 'Traditional Hoppers', 'Traditional Rice & Curry Buffet'],
      },
      {
        'name': 'Kandy Backpackers Hostel',
        'category': 'Budget',
        'description': 'A friendly hostel in the suburbs, featuring a garden pool, cozy shared lounges, and a great social vibe.',
        'rating': 4.3,
        'price': 9.0,
        'img': 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80',
        'lat': 7.2880,
        'lng': 80.6450,
        'amenities': ['Dormitory Beds', 'Swimming Pool', 'Shared Lounge', 'Free Wi-Fi'],
        'highlights': ['Suburban Garden Pool', 'Backpacker Community Vibe', 'Local Tours Bookings'],
      },
      {
        'name': 'Pink House Guesthouse',
        'category': 'Budget',
        'description': 'A long-running, friendly homestay offering clean double rooms and home-cooked family dinners.',
        'rating': 4.5,
        'price': 14.0,
        'img': 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80',
        'lat': 7.2925,
        'lng': 80.6405,
        'highlights': ['Authentic Homestyle Dinners', 'Family Run Guesthouse', 'Central Lake Location'],
      }
    ],
  },
  {
    'name': 'Arugam Bay',
    'country': 'Sri Lanka',
    'tag': 'Surf Paradise',
    'category': 'Beach',
    'tagColor': Colors.deepOrange,
    'img': 'https://images.unsplash.com/photo-1560275619-4662e36fa65c?w=800&q=80',
    'description':
        "Arugam Bay is Sri Lanka's premier surfing destination on the east coast, beloved by surf enthusiasts worldwide. This laid-back bay offers world-class point breaks, golden beaches, and a vibrant beach culture surrounded by national parks and lagoons.",
    'highlights': ['Main Point Surf Break', 'Pottuvil Lagoon', 'Elephant Safari', 'Panama Village'],
    'bestTime': 'May – Oct',
    'rating': 4.7,
    'cost': 'Free beach',
    'duration': '3-5 days',
    'lat': 6.8402,
    'lng': 81.8285,
    'subLocations': [
      {
        'name': 'Main Point Surf Break',
        'category': 'Sight',
        'description': "A world-famous right-hand point break that attracts surfers globally. The sandy bottom and long waves are ideal for intermediate to advanced riders.",
        'rating': 4.9,
        'price': 0.0,
        'img': 'https://images.unsplash.com/photo-1560275619-4662e36fa65c?w=800&q=80',
        'lat': 6.8320,
        'lng': 81.8320,
        'highlights': ['Right Hand Point Break', 'Golden Sand Coastline', 'Surf Watch Tower'],
      },
      {
        'name': 'Muhudu Maha Viharaya',
        'category': 'Sight',
        'description': 'An ancient Buddhist temple ruins situated among sand dunes on the beach. It features standing Buddha statues dating back 2000 years.',
        'rating': 4.6,
        'price': 0.0,
        'img': 'https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?w=800&q=80',
        'lat': 6.8780,
        'lng': 81.8650,
        'highlights': ['Sand Dune Ruins', 'Ancient Buddha Sculptures', 'Beachfront Historic Relics'],
      },
      {
        'name': 'Hideaway Resort',
        'category': 'Stay',
        'description': 'A beautiful family-run boutique resort nestled in lush gardens, offering eco-chic villas and a famous health cafe.',
        'rating': 4.8,
        'price': 105.0,
        'img': 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80',
        'lat': 6.8430,
        'lng': 81.8280,
        'amenities': ['Private Garden Villas', 'Organic Cafe', 'Yoga Pavilion', 'Free Wi-Fi'],
        'highlights': ['Eco-Luxury Design', 'Famous Healthy Breakfasts', 'Garden Yoga Shala'],
      },
      {
        'name': 'Blue Wave Hotel Arugambay',
        'category': 'Stay',
        'description': 'A modern 4-star resort located just minutes from the beach, featuring spacious rooms and a large swimming pool.',
        'rating': 4.5,
        'price': 90.0,
        'img': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
        'lat': 6.8465,
        'lng': 81.8260,
        'amenities': ['Swimming Pool', 'Fitness Gym', 'Cocktail Bar', 'Free Wi-Fi'],
        'highlights': ['Large Swimming Pool', 'Modern Clean Rooms', 'Centrally Located'],
      },
      {
        'name': 'Hideaway Blue Cafe',
        'category': 'Eat',
        'description': 'The most popular healthy cafe in Arugam Bay, serving cold brew coffee, fresh avo toast, and tropical fruit pancakes.',
        'rating': 4.7,
        'price': 10.0,
        'img': 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80',
        'lat': 6.8432,
        'lng': 81.8282,
        'highlights': ['Avo Toast & Eggs', 'Local Cold Brew Coffee', 'Organic Salads & Bowls'],
      },
      {
        'name': 'Seahorse Pizzeria & Bar',
        'category': 'Eat',
        'description': 'An open-air garden pizzeria famous for authentic wood-fired pizzas, fresh seafood pasta, and live acoustic music nights.',
        'rating': 4.6,
        'price': 14.0,
        'img': 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
        'lat': 6.8440,
        'lng': 81.8290,
        'highlights': ['Wood-Fired Italian Pizza', 'Garden Outdoor Seating', 'Live Acoustic Music'],
      },
      {
        'name': 'Arugam Bay Surf Camp Hostel',
        'category': 'Budget',
        'description': 'A lively budget hostel offering shared dorms, surf lessons, and communal dinners for solo backpackers.',
        'rating': 4.4,
        'price': 12.0,
        'img': 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80',
        'lat': 6.8415,
        'lng': 81.8300,
        'amenities': ['Bunk Beds', 'Shared Kitchen', 'Surf Gear Rentals', 'Free Wi-Fi'],
        'highlights': ['Surf Lessons Package', 'Social Communal Dinners', 'Hammocks Deck'],
      },
      {
        'name': 'Beach Hut Hostel',
        'category': 'Budget',
        'description': 'A rustic, budget beachfront hostel featuring wooden treehouses, cheap rooms, and a popular traveler restaurant.',
        'rating': 4.3,
        'price': 15.0,
        'img': 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80',
        'lat': 6.8385,
        'lng': 81.8315,
        'highlights': ['Rustic Wooden Cabins', 'Right on Ocean Shore', 'Social Backpacking Vibe'],
      }
    ],
  },
  {
    'name': 'Yala National Park',
    'country': 'Sri Lanka',
    'tag': 'Wildlife Safari',
    'category': 'Mountain',
    'tagColor': Colors.brown,
    'img': 'https://images.unsplash.com/photo-1705936981595-dea87508ce84?w=800&q=80',
    'description':
        "Yala National Park is Sri Lanka's most visited and second-largest national park, famous for having one of the world's highest densities of leopards. The park features diverse landscapes including forests, grasslands, and coastal wetlands, hosting elephants, sloth bears, crocodiles, and over 200 species of birds.",
    'highlights': ['Leopard Spotting', 'Elephant Herds', 'Bird Watching', 'Coastal Lagoons'],
    'bestTime': 'Feb – Jul',
    'rating': 4.9,
    'cost': '\$35 park fee',
    'duration': '1-2 days',
    'lat': 6.3776,
    'lng': 81.5034,
    'subLocations': [
      {
        'name': 'Yala Leopard Safari (Block 1)',
        'category': 'Sight',
        'description': 'A guided 4x4 open-jeep safari through Block 1, the area hosting the highest concentration of Sri Lankan leopards, wild elephants, and peacocks.',
        'rating': 4.9,
        'price': 35.0,
        'img': 'https://images.unsplash.com/photo-1705936981595-dea87508ce84?w=800&q=80',
        'lat': 6.3750,
        'lng': 81.5100,
        'highlights': ['Leopard Tracking', 'Wild Elephant Herds', '4x4 Open Jeep Experience'],
      },
      {
        'name': 'Sithulpawwa Rock Temple',
        'category': 'Sight',
        'description': 'An ancient Buddhist monastery dating back to the 2nd century BC, built atop a dramatic rock boulder deep inside the national park.',
        'rating': 4.7,
        'price': 0.0,
        'img': 'https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=800&q=80',
        'lat': 6.4250,
        'lng': 81.4500,
        'highlights': ['Buddhist Rock Monasteries', 'Stunning Peak Views', 'Elephant Crossings'],
      },
      {
        'name': 'Jetwing Yala Resort',
        'category': 'Stay',
        'description': 'A massive luxury eco-resort situated on the borders of Yala, featuring beachside pools, dune dining, and safari park drives.',
        'rating': 4.8,
        'price': 175.0,
        'img': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
        'lat': 6.3315,
        'lng': 81.4280,
        'amenities': ['Beachfront Pool', 'Safari Jeep Deck', 'Luxury Spa', 'Free Wi-Fi'],
        'highlights': ['Sand Dunes Dining', 'Wild Animals Sightings', 'Large Oceanfront Pool'],
      },
      {
        'name': 'Cinnamon Wild Yala',
        'category': 'Stay',
        'description': 'Luxury rustic game lodges placed around a natural woodland lake, offering close encounters with crocodiles and wild elephants.',
        'rating': 4.7,
        'price': 160.0,
        'img': 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
        'lat': 6.3290,
        'lng': 81.4350,
        'amenities': ['Game Chalets', 'Swimming Pool', 'Lake Observation Bar', 'Free Wi-Fi'],
        'highlights': ['Woodland Chalets', 'Crocodiles Lake View', 'Rustic Luxury Interiors'],
      },
      {
        'name': 'Yala Beach Barbecue',
        'category': 'Eat',
        'description': 'A unique beachside dining setup offering fresh grilled lobsters, prawns, and steaks with live bonfire setups next to the ocean waves.',
        'rating': 4.8,
        'price': 30.0,
        'img': 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
        'lat': 6.3312,
        'lng': 81.4284,
        'highlights': ['Fresh Grilled Lobsters', 'Bonfire Beach BBQ', 'Dinner under Stars'],
      },
      {
        'name': 'Tissamaharama Lake Restaurant',
        'category': 'Eat',
        'description': 'Scenic restaurant overlooking the ancient Tissa Wewa reservoir, serving traditional lake fish and clay-pot rice and curries.',
        'rating': 4.5,
        'price': 12.0,
        'img': 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800&q=80',
        'lat': 6.2750,
        'lng': 81.2850,
        'highlights': ['Fresh lake Fish curry', 'Reservoir Water Views', 'Authentic Sri Lankan Desserts'],
      },
      {
        'name': 'Yala Safari Camping Tent',
        'category': 'Budget',
        'description': 'A budget-friendly safari tent setup outside the park boundaries, offering rustic beds, shared campfire, and park tours.',
        'rating': 4.4,
        'price': 22.0,
        'img': 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80',
        'lat': 6.3050,
        'lng': 81.3650,
        'amenities': ['Camping Bed', 'Shared Campfire', 'Barbecue Station', 'Free Wi-Fi'],
        'highlights': ['Jungle Campfire Nights', 'Shared Safari Jeeps', 'Rustic Wilderness Vibe'],
      },
      {
        'name': 'Elephant Trail Guesthouse',
        'category': 'Budget',
        'description': 'A clean, simple budget guesthouse in Tissamaharama offering cheap private rooms and safari planning assistance.',
        'rating': 4.5,
        'price': 18.0,
        'img': 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80',
        'lat': 6.2820,
        'lng': 81.2910,
        'highlights': ['Cheapest Private Rooms', 'Safari Jeeps Booking Office', 'Friendly Family Hosts'],
      }
    ],
  },
  {
    'name': 'Trincomalee',
    'country': 'Sri Lanka',
    'tag': 'Coastal Gem',
    'category': 'Beach',
    'tagColor': Colors.teal,
    'img': 'https://images.unsplash.com/photo-1695090177375-0351b2314e3a?w=800&q=80',
    'description':
        "Trincomalee on Sri Lanka's northeast coast boasts some of the country's most pristine beaches, historic temples, and one of the world's finest deep-water harbours. Nilaveli and Uppuveli beaches offer crystal-clear waters perfect for snorkelling and diving, while the ancient Koneswaram Temple crowns the dramatic Swami Rock clifftop.",
    'highlights': ['Nilaveli Beach', 'Koneswaram Temple', 'Pigeon Island Snorkelling', 'Whale Watching'],
    'bestTime': 'Apr – Sep',
    'rating': 4.6,
    'cost': 'Free – \$20',
    'duration': '2-3 days',
    'lat': 8.5875,
    'lng': 81.2152,
    'subLocations': [
      {
        'name': 'Koneswaram Temple',
        'category': 'Sight',
        'description': 'A classical medieval Hindu temple complex built atop Swami Rock clifftop. Surrounded by dramatic cliffs dropping into the Indian ocean.',
        'rating': 4.9,
        'price': 0.0,
        'img': 'https://images.unsplash.com/photo-1558446791-ac5fec3caddf?w=800&q=80',
        'lat': 8.5775,
        'lng': 81.2442,
        'highlights': ['Swami Rock Cliffs Drop', 'Giant Gold Lord Shiva Statue', 'Historic Port of Trincomalee Views'],
      },
      {
        'name': 'Pigeon Island National Park',
        'category': 'Sight',
        'description': 'A marine national park hosting a crystal clear reef sanctuary, offering the best snorkeling in Sri Lanka with blacktip sharks.',
        'rating': 4.8,
        'price': 20.0,
        'img': 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800&q=80',
        'lat': 8.7215,
        'lng': 81.2018,
        'highlights': ['Reef Blacktip Sharks Snorkeling', 'Vibrant Sea Corals Reef', 'Boat Transport Ride'],
      },
      {
        'name': 'Trinco Blu by Cinnamon',
        'category': 'Stay',
        'description': 'A retro-chic beach resort on Uppuveli beach offering cozy chalets, diving classes, and whale watching charters.',
        'rating': 4.7,
        'price': 125.0,
        'img': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
        'lat': 8.6120,
        'lng': 81.2165,
        'amenities': ['Beachfront Chalets', 'Swimming Pool', 'PADI Dive Center', 'Free Wi-Fi'],
        'highlights': ['Retro-chic Design', 'Dolphin & Whale charters', 'Seafront Dining'],
      },
      {
        'name': 'Nilaveli Beach Hotel',
        'category': 'Stay',
        'description': 'An iconic resort directly located on the white sands of Nilaveli, offering large lawns, pools, and views of Pigeon Island.',
        'rating': 4.6,
        'price': 110.0,
        'img': 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
        'lat': 8.7095,
        'lng': 81.1960,
        'amenities': ['Lawn Gardens', 'Outdoor Pool', 'Beach Access', 'Free Wi-Fi'],
        'highlights': ['Direct Nilaveli Sand Access', 'Quiet Gardens lawns', 'Seafood Buffet'],
      },
      {
        'name': 'Dutch Bank Cafe',
        'category': 'Eat',
        'description': 'A beautiful colonial café situated on the inner harbor lagoon, serving international breakfasts, iced coffees, and local crab rolls.',
        'rating': 4.6,
        'price': 12.0,
        'img': 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80',
        'lat': 8.5720,
        'lng': 81.2310,
        'highlights': ['Colonial Dutch Building', 'Inner Harbor Lagoon Views', 'Ceylon Tea & Pastries'],
      },
      {
        'name': 'Uppuveli Crab Restaurant',
        'category': 'Eat',
        'description': 'A beach shack diner famous for Sri Lankan black pepper crab, garlic prawns, and chilled local juices under coconut palms.',
        'rating': 4.5,
        'price': 18.0,
        'img': 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
        'lat': 8.6130,
        'lng': 81.2160,
        'highlights': ['Black Pepper Crab Special', 'Beach Shack Tables', 'Fresh Catch Barbecue'],
      },
      {
        'name': 'Nilaveli Backpackers Hostel',
        'category': 'Budget',
        'description': 'A highly rated budget hostel offering bunk beds, shared kitchen, and budget boat rides to Pigeon Island.',
        'rating': 4.4,
        'price': 12.0,
        'img': 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80',
        'lat': 8.7015,
        'lng': 81.1930,
        'amenities': ['Bunk Beds', 'Shared Kitchen', 'Lounge Deck', 'Free Wi-Fi'],
        'highlights': ['Cheap Pigeon Island Transfers', 'Backpacker Community', 'Garden BBQ Nights'],
      },
      {
        'name': 'Trinco Green Guesthouse',
        'category': 'Budget',
        'description': 'A clean, simple homestay run by a welcoming local family near the Trincomalee railway station.',
        'rating': 4.5,
        'price': 16.0,
        'img': 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80',
        'lat': 8.5780,
        'lng': 81.2220,
        'highlights': ['Traditional Breakfasts included', 'Friendly Family Hosts', 'Cheap Bicycle Hire'],
      }
    ],
  },
  {
    'name': 'Dambulla Cave Temple',
    'country': 'Sri Lanka',
    'tag': 'Sacred Caves',
    'category': 'Temple',
    'tagColor': Colors.amber,
    'img': 'https://images.unsplash.com/photo-1656497107500-a2bc32cbe7d4?w=800&q=80',
    'description':
        "The Dambulla Cave Temple, also known as the Golden Temple of Dambulla, is a UNESCO World Heritage Site featuring five magnificent cave temples cut into a massive granite outcrop. The caves are adorned with 153 Buddha statues, 3 statues of Sri Lankan kings, and 4 statues of Hindu deities, surrounded by magnificent ancient frescoes.",
    'highlights': ['5 Cave Temples', '153 Buddha Statues', 'Ancient Frescoes', 'Panoramic Views'],
    'bestTime': 'Jan – Apr',
    'rating': 4.8,
    'cost': '\$10 entry',
    'duration': 'Half day',
    'lat': 7.8566,
    'lng': 80.6485,
    'subLocations': [
      {
        'name': 'Golden Temple Cave Complex',
        'category': 'Sight',
        'description': 'The core five caves cut into the 160m rock face, displaying magnificent ancient paintings, carvings, and 153 Buddha statues.',
        'rating': 4.9,
        'price': 10.0,
        'img': 'https://images.unsplash.com/photo-1656497107500-a2bc32cbe7d4?w=800&q=80',
        'lat': 7.8560,
        'lng': 80.6488,
        'highlights': ['5 Ancient Rock Caves', '153 Standing Buddha Statues', 'Historic Frescoes Walls'],
      },
      {
        'name': "Popham's Arboretum",
        'category': 'Sight',
        'description': 'Sri Lanka\'s unique dry zone arboretum, offering guided night walks to spot the rare gray slender loris in the wild.',
        'rating': 4.6,
        'price': 6.0,
        'img': 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80',
        'lat': 7.8810,
        'lng': 80.6720,
        'highlights': ['Slender Loris Night Walk', 'Dry Zone Forest Path', 'Eco Conservation Site'],
      },
      {
        'name': 'Heritance Kandalama',
        'category': 'Stay',
        'description': 'An architectural masterpiece by Geoffrey Bawa, built into a rock face and offering stunning views of the Sigiriya rock and Kandalama tank.',
        'rating': 4.9,
        'price': 250.0,
        'img': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
        'lat': 7.8893,
        'lng': 80.7258,
        'amenities': ['Infinity Pools', 'Eco Forest Park', 'Spa Wellness', 'Fine Dining Room'],
        'highlights': ['Geoffrey Bawa Rock Architecture', 'Infinity Pools Overlooking Lake', 'Wild Monkeys & Birds Spotting'],
      },
      {
        'name': 'Amaya Lake Dambulla',
        'category': 'Stay',
        'description': 'A peaceful lakeside resort featuring traditional clay villas, lush gardens, and Ayurvedic spa wellness programs.',
        'rating': 4.7,
        'price': 120.0,
        'img': 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
        'lat': 7.8920,
        'lng': 80.6220,
        'amenities': ['Swimming Pool', 'Ayurveda Spa', 'Lakeside Walks', 'Free Wi-Fi'],
        'highlights': ['Rustic Clay Cottages', 'Scenic Lake Reservoir Views', 'Traditional Treatments'],
      },
      {
        'name': 'Gimanhala Restaurant',
        'category': 'Eat',
        'description': 'A popular stopover restaurant serving authentic Sri Lankan rice and curry buffers, short-eats, and fresh tropical fruit juices.',
        'rating': 4.4,
        'price': 9.0,
        'img': 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
        'lat': 7.8720,
        'lng': 80.6510,
        'highlights': ['Ceylon Spiced Curries', 'Fruit Juices Bar', 'Scenic Valley Terrace'],
      },
      {
        'name': 'Bentota Bake House Dambulla',
        'category': 'Eat',
        'description': 'A clean local bakery and cafe offering fresh short-eats, kottu roti, hoppers, and local tea in a casual setting.',
        'rating': 4.3,
        'price': 6.0,
        'img': 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800&q=80',
        'lat': 7.8630,
        'lng': 80.6500,
        'highlights': ['Spicy Kottu Roti', 'Samosas & short-eats', 'Local Milk Tea'],
      },
      {
        'name': 'Dambulla Youth Hostel',
        'category': 'Budget',
        'description': 'A budget-friendly hostel offering clean shared dorms, free Wi-Fi, and rental bicycles to explore Dambulla.',
        'rating': 4.4,
        'price': 11.0,
        'img': 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80',
        'lat': 7.8600,
        'lng': 80.6460,
        'amenities': ['Bunk Beds', 'Bicycle Rental', 'Free Wi-Fi', 'Shared Kitchen'],
        'highlights': ['Cheapest Dorms Rooms', 'Free Bicycles Maps', 'Social Gathering Area'],
      },
      {
        'name': 'Golden Homestay Dambulla',
        'category': 'Budget',
        'description': 'A warm, welcoming homestay located close to the Golden Buddha statue, offering traditional home-cooked foods.',
        'rating': 4.6,
        'price': 14.0,
        'img': 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80',
        'lat': 7.8540,
        'lng': 80.6495,
        'highlights': ['Home Cooked Claypot Dinner', '2 Minutes Walk to Temple', 'Welcoming Local Family'],
      }
    ],
  },
  {
    'name': 'Nuwara Eliya',
    'country': 'Sri Lanka',
    'tag': 'Little England',
    'category': 'Mountain',
    'tagColor': Colors.indigo,
    'img': 'https://images.unsplash.com/photo-1760533852055-724d3a50dcbd?w=800&q=80',
    'description':
        'Nuwara Eliya, known as "Little England," sits at 1,868m in Sri Lanka\'s tea country. This cool hill station features colonial-era bungalows, manicured gardens, and the world-famous Ceylon tea estates. The scenic train journey to Nuwara Eliya through mist-covered mountains is considered one of the most beautiful rail trips in the world.',
    'highlights': ['Tea Factory Tours', 'Gregory Lake', 'Hakgala Gardens', 'Train Journey'],
    'bestTime': 'Jan – Apr',
    'rating': 4.7,
    'cost': '\$5 - \$15 tours',
    'duration': '2 days',
    'lat': 6.9497,
    'lng': 80.7828,
    'subLocations': [
      {
        'name': 'Gregory Lake Park',
        'category': 'Sight',
        'description': 'A scenic lake in the heart of town offering motorboat rides, pony riding, and peaceful lakeside pathways.',
        'rating': 4.6,
        'price': 2.0,
        'img': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
        'lat': 6.9642,
        'lng': 80.7853,
        'highlights': ['Lakeside Walking Path', 'Pony Rides for Kids', 'Motorboat Rentals'],
      },
      {
        'name': 'Pedro Tea Estate',
        'category': 'Sight',
        'description': 'An authentic tea estate established in 1885. Take a guided tour to see the processing of world-famous Ceylon tea.',
        'rating': 4.7,
        'price': 5.0,
        'img': 'https://images.unsplash.com/photo-1760533852055-724d3a50dcbd?w=800&q=80',
        'lat': 6.9785,
        'lng': 80.8090,
        'highlights': ['19th Century Tea Factory Tour', 'Tea Plucking Experience', 'Fresh Brew Tasting Cafe'],
      },
      {
        'name': 'The Grand Hotel',
        'category': 'Stay',
        'description': 'An iconic, historic Elizabethan-era manor featuring beautiful rose gardens, high tea, and premium fine dining.',
        'rating': 4.8,
        'price': 180.0,
        'img': 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80',
        'lat': 6.9692,
        'lng': 80.7675,
        'amenities': ['English Rose Gardens', 'High Tea Lounge', 'Wine Cellar Bar', 'Free Wi-Fi'],
        'highlights': ['Elizabethan-era Manor', 'Famous Afternoon High Tea', 'Billiard Room'],
      },
      {
        'name': 'Heritance Tea Factory',
        'category': 'Stay',
        'description': 'A converted 19th-century tea factory nestled in the mountains, offering colonial character and tea-plucking tours.',
        'rating': 4.8,
        'price': 155.0,
        'img': 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
        'lat': 7.0255,
        'lng': 80.8385,
        'amenities': ['Tea Packing Bar', 'Historic Dining Carriage', 'Spa Resort', 'Free Wi-Fi'],
        'highlights': ['Converted Factory Building', 'Mist Mountain Views', 'Organic Tea Plucking'],
      },
      {
        'name': 'Grand Indian Restaurant',
        'category': 'Eat',
        'description': 'The most popular Indian restaurant in Nuwara Eliya, famous for butter chicken, garlic naan, and mutton biryani.',
        'rating': 4.6,
        'price': 14.0,
        'img': 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80',
        'lat': 6.9690,
        'lng': 80.7672,
        'highlights': ['Spiced Butter Chicken', 'Garlic Naan Bread', 'Popular Curry Corner'],
      },
      {
        'name': 'Barnes Hall Dining Room',
        'category': 'Eat',
        'description': 'An upscale restaurant at the Grand Hotel, serving international gourmet buffets and local Ceylon tea-infused dishes.',
        'rating': 4.5,
        'price': 20.0,
        'img': 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
        'lat': 6.9688,
        'lng': 80.7680,
        'highlights': ['International Buffet', 'Colonial Dining Rooms', 'Traditional English Desserts'],
      },
      {
        'name': 'Nuwara Eliya Youth Hostel',
        'category': 'Budget',
        'description': 'A cozy, warm hostel located close to Victoria Park, featuring budget dorms and hot water showers.',
        'rating': 4.4,
        'price': 11.0,
        'img': 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80',
        'lat': 6.9720,
        'lng': 80.7710,
        'amenities': ['Bunk Beds', 'Hot Water Showers', 'Shared Kitchen', 'Free Wi-Fi'],
        'highlights': ['Victoria Park Proximity', 'Shared Lounge Fireplace', 'Cheapest Dorm Beds'],
      },
      {
        'name': 'Single Tree Guesthouse',
        'category': 'Budget',
        'description': 'A clean, peaceful guesthouse run by friendly locals, located at the base of Single Tree mountain.',
        'rating': 4.3,
        'price': 18.0,
        'img': 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80',
        'lat': 6.9610,
        'lng': 80.7750,
        'highlights': ['Mountain Base Views', 'Traditional Sri Lankan Tea', 'Clean Quiet Rooms'],
      }
    ],
  },
  {
    'name': 'Hikkaduwa',
    'country': 'Sri Lanka',
    'tag': 'Beach & Coral Reefs',
    'category': 'Beach',
    'tagColor': Colors.teal,
    'img': 'https://images.unsplash.com/photo-1743523477913-87bbfb7ebeaa?w=800&q=80',
    'description':
        'Hikkaduwa is a famous beach town on the southern coast of Sri Lanka. Renowned for its beautiful sandy beaches, excellent surf breaks, vibrant nightlife, and a sanctuary of coral reefs and giant sea turtles that swim close to the shore.',
    'highlights': ['Coral Reef Sanctuary', 'Turtle Hatchery', 'Surfing at Benny\'s', 'Beach Nightlife'],
    'bestTime': 'Nov – Apr',
    'rating': 4.8,
    'cost': 'Free beach',
    'duration': '2-3 days',
    'lat': 6.1360,
    'lng': 80.1044,
    'subLocations': [
      {
        'name': 'Hikkaduwa Coral Sanctuary',
        'category': 'Sight',
        'description': 'A marine sanctuary hosting a large shallow area with colorful corals and sea turtles. Perfect for snorkeling and glass-bottom boat rides.',
        'rating': 4.7,
        'price': 5.0,
        'img': 'https://images.unsplash.com/photo-1546026423-cc4642628d2b?w=800&q=80',
        'lat': 6.1396,
        'lng': 80.0984,
        'highlights': ['Colorful Corals', 'Snorkeling', 'Glass Bottom Boats', 'Giant Turtles'],
      },
      {
        'name': 'Turtle Hatchery & Sanctuary',
        'category': 'Sight',
        'description': 'A conservation project dedicated to protecting turtle eggs and releasing baby turtles into the wild. Learn about marine conservation.',
        'rating': 4.6,
        'price': 3.0,
        'img': 'https://images.unsplash.com/photo-1559583985-c80d8ad9b29f?w=800&q=80',
        'lat': 6.1601,
        'lng': 80.0942,
        'highlights': ['Baby Turtles', 'Conservation Education', 'Turtle Release', 'Volunteer Projects'],
      },
      {
        'name': 'Hikkaduwa Lake',
        'category': 'Sight',
        'description': 'A tranquil lake popular for bird watching, canoeing, and peaceful nature walks away from the busy beach.',
        'rating': 4.4,
        'price': 0.0,
        'img': 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80',
        'lat': 6.1420,
        'lng': 80.1150,
        'highlights': ['Bird Watching', 'Canoeing', 'Tranquil Views', 'Nature Trails'],
      },
      {
        'name': 'Hikka Tranz by Cinnamon',
        'category': 'Stay',
        'description': 'Vibrant beachside resort offering luxury rooms, sea views, a huge pool, and direct access to turtle feeding spots.',
        'rating': 4.8,
        'price': 140.0,
        'img': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
        'lat': 6.1368,
        'lng': 80.1030,
        'amenities': ['Infinity Pool', 'Direct Beach Access', 'Spa', 'Multiple Bars', 'Gym'],
        'highlights': ['Beachfront Pool', 'Sea Turtle Feeding', 'Modern Rooms', 'Cocktails'],
      },
      {
        'name': 'Citrus Hikkaduwa',
        'category': 'Stay',
        'description': 'Beautiful beach resort with modern design, beachfront restaurant, and comfortable rooms.',
        'rating': 4.5,
        'price': 95.0,
        'img': 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
        'lat': 6.1399,
        'lng': 80.1005,
        'amenities': ['Pool', 'Beachfront Dining', 'Spa', 'Free Wi-Fi', 'Bar'],
        'highlights': ['Sunset Views', 'Oceanfront Dining', 'Friendly Service'],
      },
      {
        'name': 'Refresh Restaurant',
        'category': 'Eat',
        'description': 'Famous for fresh seafood, Sri Lankan rice and curry, and Western dishes with ocean views.',
        'rating': 4.6,
        'price': 15.0,
        'img': 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
        'lat': 6.1408,
        'lng': 80.0995,
        'highlights': ['Fresh Seafood', 'Ocean Views', 'Local Curries', 'Vibrant Atmosphere'],
      },
      {
        'name': 'Spaghetti & Co.',
        'category': 'Eat',
        'description': 'Top-rated Italian restaurant serving wood-fired pizzas and fresh handmade pasta in a cozy setting.',
        'rating': 4.7,
        'price': 18.0,
        'img': 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800&q=80',
        'lat': 6.1432,
        'lng': 80.0980,
        'highlights': ['Wood-fired Pizza', 'Handmade Pasta', 'Italian Wine', 'Cozy Garden'],
      },
      {
        'name': 'Hikka Surf Hostel',
        'category': 'Budget',
        'description': 'A friendly, budget-friendly hostel popular among backpackers and surfers, with shared kitchen and social lobby.',
        'rating': 4.4,
        'price': 12.0,
        'img': 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80',
        'lat': 6.1350,
        'lng': 80.1040,
        'amenities': ['Free Wi-Fi', 'Shared Kitchen', 'Locker Room', 'Surf Board Rentals'],
        'highlights': ['Surfer Vibe', 'Backpacker Community', 'Cheap Beds'],
      },
      {
        'name': 'J.L.H. Beach Guesthouse',
        'category': 'Budget',
        'description': 'Simple, clean beachfront rooms run by a hospitable local family.',
        'rating': 4.3,
        'price': 20.0,
        'img': 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80',
        'lat': 6.1402,
        'lng': 80.1001,
        'highlights': ['Beachfront Rooms', 'Local Family Run', 'Great Hospitality'],
      }
    ],
  },
];

// Helper function to return categorized sub-locations, fallback if missing
List<Map<String, dynamic>> getSubLocations(Map<String, dynamic> dest) {
  if (dest.containsKey('subLocations') && dest['subLocations'] is List) {
    return List<Map<String, dynamic>>.from(dest['subLocations'] as List);
  }
  
  // Dynamic fallback generator based on destination name
  final name = dest['name'] as String? ?? 'Destination';
  final baseLat = dest['lat'] as double? ?? 6.9271;
  final baseLng = dest['lng'] as double? ?? 79.8612;

  return [
    {
      'name': '$name Heritage Tour',
      'category': 'Sight',
      'description': 'Explore the history, landmarks, and cultural legacy of $name with an experienced local guide.',
      'rating': 4.7,
      'price': 10.0,
      'img': 'https://images.unsplash.com/photo-1566296314736-6eaac1ca0cb9?w=800&q=80',
      'lat': baseLat + 0.005,
      'lng': baseLng - 0.003,
      'highlights': ['Cultural Insights', 'Historical Landmarks', 'Local Tour Guide'],
    },
    {
      'name': '$name Scenic View Point',
      'category': 'Sight',
      'description': 'Hike up to the most famous viewpoints in $name to capture breathtaking panoramic sunset photos.',
      'rating': 4.6,
      'price': 0.0,
      'img': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
      'lat': baseLat - 0.004,
      'lng': baseLng + 0.006,
      'highlights': ['Sunset Views', 'Scenic Hike', 'Photography Spot'],
    },
    {
      'name': '$name Retreat & Spa',
      'category': 'Stay',
      'description': 'Enjoy a premium, relaxing stay surrounded by the beautiful natural landscapes of $name.',
      'rating': 4.8,
      'price': 120.0,
      'img': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
      'lat': baseLat + 0.002,
      'lng': baseLng + 0.002,
      'amenities': ['Swimming Pool', 'Luxury Spa', 'Free Wi-Fi', 'Restaurant'],
      'highlights': ['Luxury Chalets', 'Stunning Views', 'Relaxing Ambiance'],
    },
    {
      'name': '$name Colonial Inn',
      'category': 'Stay',
      'description': 'A heritage property blending historic charm with modern comfort in the heart of $name.',
      'rating': 4.4,
      'price': 75.0,
      'img': 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
      'lat': baseLat - 0.002,
      'lng': baseLng - 0.002,
      'amenities': ['Heritage Architecture', 'Restaurant', 'Free Wi-Fi'],
      'highlights': ['Colonial Style', 'Cozy Atmosphere', 'Central Location'],
    },
    {
      'name': '$name Ocean View Restaurant',
      'category': 'Eat',
      'description': 'Taste the freshest seafood catches and authentic Sri Lankan spices overlooking the sea in $name.',
      'rating': 4.5,
      'price': 22.0,
      'img': 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
      'lat': baseLat + 0.001,
      'lng': baseLng - 0.005,
      'highlights': ['Seafront Dining', 'Signature Seafood Platters', 'Tropical Cocktails'],
    },
    {
      'name': '$name Spice Garden Cafe',
      'category': 'Eat',
      'description': 'A beautiful garden café serving organic breakfasts, local teas, and healthy vegan-friendly options.',
      'rating': 4.6,
      'price': 12.0,
      'img': 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800&q=80',
      'lat': baseLat - 0.006,
      'lng': baseLng + 0.001,
      'highlights': ['Organic Produce', 'Ceylon Tea Tasting', 'Cozy Garden Vibes'],
    },
    {
      'name': '$name Backpackers Hostel',
      'category': 'Budget',
      'description': 'A budget-friendly hostel with dormitory beds, shared bathrooms, and a highly social vibe for solo travelers.',
      'rating': 4.3,
      'price': 15.0,
      'img': 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80',
      'lat': baseLat + 0.004,
      'lng': baseLng + 0.004,
      'amenities': ['Bunk Beds', 'Shared Lounge', 'Free Wi-Fi', 'Locker System'],
      'highlights': ['Budget Friendly', 'Social Atmosphere', 'Backpacker Community'],
    },
    {
      'name': '$name Green Guesthouse',
      'category': 'Budget',
      'description': 'An eco-friendly homestay offering comfortable private rooms run by a welcoming local family.',
      'rating': 4.5,
      'price': 25.0,
      'img': 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80',
      'lat': baseLat - 0.005,
      'lng': baseLng - 0.004,
      'highlights': ['Eco-friendly', 'Family Hospitality', 'Traditional Breakfast'],
    }
  ];
}
