import 'package:flutter/material.dart';

// ─────────────────────────────────────────────
// DATA — Sri Lanka destinations (expanded per Figma)
// ─────────────────────────────────────────────
final List<Map<String, dynamic>> kDestinations = [
  {
    'name': 'Sigiriya',
    'country': 'Sri Lanka',
    'tag': 'Ancient Wonder',
    'category': 'Mountain',
    'tagColor': Colors.orange,
    'img': 'https://images.unsplash.com/photo-1586902197503-e71026292412?w=800&q=80',
    'description':
        'Sigiriya is an ancient rock fortress in the Matale District of Sri Lanka. Rising nearly 200 metres above the surrounding plains, this UNESCO World Heritage Site features the remains of a 5th-century royal palace, stunning frescoes, mirror walls, and beautifully landscaped water gardens.',
    'highlights': ['Lion Rock Summit', 'Ancient Frescoes', 'Water Gardens', 'Mirror Wall'],
    'bestTime': 'Jan – Apr',
    'rating': 4.9,
    'cost': '\$25 entry',
    'duration': '1 day',
  },
  {
    'name': 'Ella',
    'country': 'Sri Lanka',
    'tag': 'Hill Country',
    'category': 'Mountain',
    'tagColor': Colors.green,
    'img': 'https://images.unsplash.com/photo-1590050752117-23a9d7fc91d3?auto=format&fit=crop&w=800&q=80',
    'description':
        "Ella is a small town nestled in Sri Lanka's central highlands. Famous for lush tea plantations, dramatic mountain scenery, and the iconic Nine Arch Bridge, it offers a tranquil escape into nature.",
    'highlights': ['Nine Arch Bridge', "Little Adam's Peak", 'Tea Plantations', 'Ella Rock'],
    'bestTime': 'Jan – Mar',
    'rating': 4.8,
    'cost': 'Free – \$10',
    'duration': '2-3 days',
  },
  {
    'name': 'Galle Fort',
    'country': 'Sri Lanka',
    'tag': 'Colonial Heritage',
    'category': 'Temple',
    'tagColor': Colors.blue,
    'img': 'https://images.unsplash.com/photo-1627894483216-2138af692e32?w=800&q=80',
    'description':
        'Galle Fort is a historic fortified city on the southwestern tip of Sri Lanka, built by the Portuguese and later fortified by the Dutch. This UNESCO site blends European architecture with South Asian traditions.',
    'highlights': ['Dutch Reformed Church', 'Lighthouse', 'Ocean Ramparts', 'Old Bazaar'],
    'bestTime': 'Nov – Apr',
    'rating': 4.7,
    'cost': 'Free entry',
    'duration': '1-2 days',
  },
  {
    'name': 'Mirissa Beach',
    'country': 'Sri Lanka',
    'tag': 'Coastal Paradise',
    'category': 'Beach',
    'tagColor': Colors.cyan,
    'img': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    'description':
        'Mirissa is a coastal town on the southern tip of Sri Lanka, renowned for its crescent-shaped beach, vibrant nightlife, and world-class whale watching between November and April.',
    'highlights': ['Whale Watching', 'Coconut Tree Hill', 'Surfing', 'Secret Beach'],
    'bestTime': 'Nov – Apr',
    'rating': 4.6,
    'cost': '\$30 whale tour',
    'duration': '2-3 days',
  },
  {
    'name': 'Kandy',
    'country': 'Sri Lanka',
    'tag': 'Cultural Capital',
    'category': 'Temple',
    'tagColor': Colors.purple,
    'img': 'https://images.unsplash.com/photo-1566296314736-6eaac1ca0cb9?w=800&q=80',
    'description':
        "Kandy is Sri Lanka's cultural capital, home to the sacred Temple of the Tooth Relic. Surrounded by a beautiful lake and lush mountains, the city hosts the spectacular Esala Perahera festival each year.",
    'highlights': ['Temple of the Tooth', 'Kandy Lake', 'Royal Botanical Gardens', 'Esala Perahera'],
    'bestTime': 'Jan – Apr',
    'rating': 4.8,
    'cost': '\$15 entry',
    'duration': '2 days',
  },
  {
    'name': 'Arugam Bay',
    'country': 'Sri Lanka',
    'tag': 'Surf Paradise',
    'category': 'Beach',
    'tagColor': Colors.deepOrange,
    'img': 'https://images.unsplash.com/photo-1560275619-4662e36fa65c?w=800&q=80',
    'description':
        "Arugam Bay is Sri Lanka's premier surfing destination on the east coast, beloved by surf enthusiasts worldwide. This laid-back bay offers world-class point breaks, golden beaches, and a vibrant beach culture surrounded by national parks and lagoons.",
    'highlights': ['Main Point Surf Break', 'Pottuvil Lagoon', 'Elephant Safari', 'Panama Village'],
    'bestTime': 'May – Oct',
    'rating': 4.7,
    'cost': 'Free beach',
    'duration': '3-5 days',
  },
  {
    'name': 'Yala National Park',
    'country': 'Sri Lanka',
    'tag': 'Wildlife Safari',
    'category': 'Mountain',
    'tagColor': Colors.brown,
    'img': 'https://images.unsplash.com/photo-1549366021-9f761d450615?w=800&q=80',
    'description':
        "Yala National Park is Sri Lanka's most visited and second-largest national park, famous for having one of the world's highest densities of leopards. The park features diverse landscapes including forests, grasslands, and coastal wetlands, hosting elephants, sloth bears, crocodiles, and over 200 species of birds.",
    'highlights': ['Leopard Spotting', 'Elephant Herds', 'Bird Watching', 'Coastal Lagoons'],
    'bestTime': 'Feb – Jul',
    'rating': 4.9,
    'cost': '\$35 park fee',
    'duration': '1-2 days',
  },
  {
    'name': 'Trincomalee',
    'country': 'Sri Lanka',
    'tag': 'Coastal Gem',
    'category': 'Beach',
    'tagColor': Colors.teal,
    'img': 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800&q=80',
    'description':
        "Trincomalee on Sri Lanka's northeast coast boasts some of the country's most pristine beaches, historic temples, and one of the world's finest deep-water harbours. Nilaveli and Uppuveli beaches offer crystal-clear waters perfect for snorkelling and diving, while the ancient Koneswaram Temple crowns the dramatic Swami Rock clifftop.",
    'highlights': ['Nilaveli Beach', 'Koneswaram Temple', 'Pigeon Island Snorkelling', 'Whale Watching'],
    'bestTime': 'Apr – Sep',
    'rating': 4.6,
    'cost': 'Free – \$20',
    'duration': '2-3 days',
  },
  {
    'name': 'Dambulla Cave Temple',
    'country': 'Sri Lanka',
    'tag': 'Sacred Caves',
    'category': 'Temple',
    'tagColor': Colors.amber,
    'img': 'https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=800&q=80',
    'description':
        "The Dambulla Cave Temple, also known as the Golden Temple of Dambulla, is a UNESCO World Heritage Site featuring five magnificent cave temples cut into a massive granite outcrop. The caves are adorned with 153 Buddha statues, 3 statues of Sri Lankan kings, and 4 statues of Hindu deities, surrounded by magnificent ancient frescoes.",
    'highlights': ['5 Cave Temples', '153 Buddha Statues', 'Ancient Frescoes', 'Panoramic Views'],
    'bestTime': 'Jan – Apr',
    'rating': 4.8,
    'cost': '\$10 entry',
    'duration': 'Half day',
  },
  {
    'name': 'Nuwara Eliya',
    'country': 'Sri Lanka',
    'tag': 'Little England',
    'category': 'Mountain',
    'tagColor': Colors.indigo,
    'img': 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80',
    'description':
        'Nuwara Eliya, known as "Little England," sits at 1,868m in Sri Lanka\'s tea country. This cool hill station features colonial-era bungalows, manicured gardens, and the world-famous Ceylon tea estates. The scenic train journey to Nuwara Eliya through mist-covered mountains is considered one of the most beautiful rail trips in the world.',
    'highlights': ['Tea Factory Tours', 'Gregory Lake', 'Hakgala Gardens', 'Train Journey'],
    'bestTime': 'Jan – Apr',
    'rating': 4.7,
    'cost': '\$5-15 tours',
    'duration': '2 days',
  },
];
