// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvqCZfx7RnBFRmkSzExHVmxvdV9bM30g0',
    appId: '1:804161731157:web:f8d874ffe34cadd0a4f2dc',
    messagingSenderId: '804161731157',
    projectId: 'travel-ai-guide-90ce8',
    authDomain: 'travel-ai-guide-90ce8.firebaseapp.com',
    storageBucket: 'travel-ai-guide-90ce8.firebasestorage.app',
    measurementId: 'G-5EKXXY9GRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGr4CX0Y60w0c58xsSPvqaWCgT_p33JmE',
    appId: '1:804161731157:android:dae12467f57ac5b9a4f2dc',
    messagingSenderId: '804161731157',
    projectId: 'travel-ai-guide-90ce8',
    storageBucket: 'travel-ai-guide-90ce8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX7kawnBoRL2iYHfOkQcHNVwW7aTCVEDM',
    appId: '1:804161731157:ios:ca179acbc1906397a4f2dc',
    messagingSenderId: '804161731157',
    projectId: 'travel-ai-guide-90ce8',
    storageBucket: 'travel-ai-guide-90ce8.firebasestorage.app',
    iosBundleId: 'com.example.myTravelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX7kawnBoRL2iYHfOkQcHNVwW7aTCVEDM',
    appId: '1:804161731157:ios:ca179acbc1906397a4f2dc',
    messagingSenderId: '804161731157',
    projectId: 'travel-ai-guide-90ce8',
    storageBucket: 'travel-ai-guide-90ce8.firebasestorage.app',
    iosBundleId: 'com.example.myTravelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvqCZfx7RnBFRmkSzExHVmxvdV9bM30g0',
    appId: '1:804161731157:web:ea05eaa96f33092aa4f2dc',
    messagingSenderId: '804161731157',
    projectId: 'travel-ai-guide-90ce8',
    authDomain: 'travel-ai-guide-90ce8.firebaseapp.com',
    storageBucket: 'travel-ai-guide-90ce8.firebasestorage.app',
    measurementId: 'G-41TT4T3CQT',
  );
}
